const sampleAirman = [
    {
        airmanId: 1,
        firstName: 'Brown',
        lastName: 'Avacado',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['basket-weeving','cross-fit'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    {
        airmanId: 2,
        firstName: 'Yellow',
        lastName: 'Banana',
        middleInitial: 'C',
        rank: 'Amn',
        flight: 'DGK',
        afsc: '0M38G',
        squadron: '875MS',
        deros: "2022-02-02",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['hanging out on brittle branches','doing the split'],
        tasksCurrent: [],
        tasksCompleted: ['pie eating contest']
    },
    {
        airmanId: 3,
        firstName: 'Good',
        lastName: 'Blackberry',
        middleInitial: 'C',
        rank: 'SrA',
        flight: 'DMV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2023-03-03",
        bio: 'I come in clusters.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['making people healthy','running'],
        tasksCurrent: ['make smoothies'],
        tasksCompleted: ['running track']
    },
    {
        airmanId: 4,
        firstName: 'Snow',
        lastName: 'Crab-Apple',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2022-22-02",
        bio: 'I grew up in the depths of the Pacific Ocean.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['bottom feeding','being crabby'],
        tasksCurrent: ['find treasures at the bottom of the Atlantic Ocean'],
        tasksCompleted: ['found treasures at the bottom of the Pacific Ocean']
    },
    {
        airmanId: 5,
        firstName: 'Brown',
        lastName: 'Avacado',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['basket-weeving','cross-fit'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    {
        airmanId: 6,
        firstName: 'Green',
        lastName: 'Canteloupe',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'MVP',
        afsc: '0J387Z',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I lived most of my life surrounded by honeydews and canteloupes.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['eating','sleeping'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    {
        airmanId: 7,
        firstName: 'Brown',
        lastName: 'Avacado',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['basket-weeving','cross-fit'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    {
        airmanId: 8,
        firstName: 'Brown',
        lastName: 'Avacado',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['basket-weeving','cross-fit'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    {
        airmanId: 9,
        firstName: 'Brown',
        lastName: 'Avacado',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['basket-weeving','cross-fit'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    {
        airmanId: 10,
        firstName: 'Brown',
        lastName: 'Avacado',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['basket-weeving','cross-fit'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    {
        airmanId: 11,
        firstName: 'Brown',
        lastName: 'Avacado',
        middleInitial: 'C',
        rank: 'A1C',
        flight: 'DOV',
        afsc: '8B987A',
        squadron: '875MS',
        deros: "2021-01-01",
        bio: 'I like to grow on trees and turn brown fast.',
        imgURL: "https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_960_720.png",
        skills: ['basket-weeving','cross-fit'],
        tasksCurrent: [],
        tasksCompleted: []
    },
    
]

export default sampleAirman;